{{- /* iSCSI Storage Class */ -}}
{{- if .Values.storageClassIscsi.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassIscsi.name }}
  labels:
    {{- include "freebsd-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClassIscsi.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.driver.name }}
parameters:
  exportType: iscsi
  fsType: {{ .Values.storageClassIscsi.parameters.fsType | default "ext4" }}
  {{- if .Values.storageClassIscsi.parameters.endpoints }}
  endpoints: {{ .Values.storageClassIscsi.parameters.endpoints | quote }}
  {{- else if .Values.storageClassIscsi.parameters.portal }}
  {{/* DEPRECATED: portal is deprecated, use endpoints instead */}}
  endpoints: {{ .Values.storageClassIscsi.parameters.portal | quote }}
  {{- end }}
  {{- /* Block device configuration parameters */ -}}
  {{- if .Values.storageClassIscsi.parameters.blockSize }}
  blockSize: {{ .Values.storageClassIscsi.parameters.blockSize | quote }}
  {{- end }}
  {{- if .Values.storageClassIscsi.parameters.physicalBlockSize }}
  physicalBlockSize: {{ .Values.storageClassIscsi.parameters.physicalBlockSize | quote }}
  {{- end }}
  {{- if .Values.storageClassIscsi.parameters.enableUnmap }}
  enableUnmap: {{ .Values.storageClassIscsi.parameters.enableUnmap | quote }}
  {{- end }}
  {{- /* CHAP authentication secret parameters */ -}}
  {{- $iscsiSecretName := "" }}
  {{- $iscsiSecretNamespace := .Release.Namespace }}
  {{- if .Values.storageClassIscsi.chapSecret.name }}
  {{- $iscsiSecretName = .Values.storageClassIscsi.chapSecret.name }}
  {{- $iscsiSecretNamespace = .Values.storageClassIscsi.chapSecret.namespace | default .Release.Namespace }}
  {{- else if .Values.storageClassIscsi.chapSecret.credentials.username }}
  {{- $iscsiSecretName = printf "%s-chap" (include "freebsd-csi.fullname" .) }}
  {{- end }}
  {{- if $iscsiSecretName }}
  csi.storage.k8s.io/provisioner-secret-name: {{ $iscsiSecretName | quote }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $iscsiSecretNamespace | quote }}
  csi.storage.k8s.io/node-stage-secret-name: {{ $iscsiSecretName | quote }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $iscsiSecretNamespace | quote }}
  csi.storage.k8s.io/node-publish-secret-name: {{ $iscsiSecretName | quote }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $iscsiSecretNamespace | quote }}
  {{- end }}
allowVolumeExpansion: {{ .Values.storageClassIscsi.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClassIscsi.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClassIscsi.volumeBindingMode }}
---
{{- end }}
{{- /* NVMeoF Storage Class */ -}}
{{- if .Values.storageClassNvmeof.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassNvmeof.name }}
  labels:
    {{- include "freebsd-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClassNvmeof.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.driver.name }}
parameters:
  exportType: nvmeof
  fsType: {{ .Values.storageClassNvmeof.parameters.fsType | default "ext4" }}
  {{- if .Values.storageClassNvmeof.parameters.endpoints }}
  endpoints: {{ .Values.storageClassNvmeof.parameters.endpoints | quote }}
  {{- else if .Values.storageClassNvmeof.parameters.transportAddr }}
  {{- /* DEPRECATED: transportAddr/transportPort are deprecated, use endpoints instead */ -}}
  {{- $port := .Values.storageClassNvmeof.parameters.transportPort | default "4420" }}
  {{- $addrs := splitList "," .Values.storageClassNvmeof.parameters.transportAddr }}
  {{- $endpoints := list }}
  {{- range $addrs }}
  {{- $endpoints = append $endpoints (printf "%s:%s" (trim .) $port) }}
  {{- end }}
  endpoints: {{ join "," $endpoints | quote }}
  {{- end }}
  {{- /* Block device configuration parameters */ -}}
  {{- if .Values.storageClassNvmeof.parameters.blockSize }}
  blockSize: {{ .Values.storageClassNvmeof.parameters.blockSize | quote }}
  {{- end }}
  {{- if .Values.storageClassNvmeof.parameters.physicalBlockSize }}
  physicalBlockSize: {{ .Values.storageClassNvmeof.parameters.physicalBlockSize | quote }}
  {{- end }}
  {{- if .Values.storageClassNvmeof.parameters.enableUnmap }}
  enableUnmap: {{ .Values.storageClassNvmeof.parameters.enableUnmap | quote }}
  {{- end }}
  {{- /* NVMeoF DH-HMAC-CHAP authentication secret parameters */ -}}
  {{- $nvmeSecretName := "" }}
  {{- $nvmeSecretNamespace := .Release.Namespace }}
  {{- if .Values.storageClassNvmeof.authSecret.name }}
  {{- $nvmeSecretName = .Values.storageClassNvmeof.authSecret.name }}
  {{- $nvmeSecretNamespace = .Values.storageClassNvmeof.authSecret.namespace | default .Release.Namespace }}
  {{- else if .Values.storageClassNvmeof.authSecret.credentials.hostNqn }}
  {{- $nvmeSecretName = printf "%s-nvme-auth" (include "freebsd-csi.fullname" .) }}
  {{- end }}
  {{- if $nvmeSecretName }}
  csi.storage.k8s.io/provisioner-secret-name: {{ $nvmeSecretName | quote }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $nvmeSecretNamespace | quote }}
  csi.storage.k8s.io/node-stage-secret-name: {{ $nvmeSecretName | quote }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $nvmeSecretNamespace | quote }}
  csi.storage.k8s.io/node-publish-secret-name: {{ $nvmeSecretName | quote }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $nvmeSecretNamespace | quote }}
  {{- end }}
allowVolumeExpansion: {{ .Values.storageClassNvmeof.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClassNvmeof.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClassNvmeof.volumeBindingMode }}
{{- end }}
