{{- /* iSCSI Storage Class */ -}}
{{- if .Values.storageClassIscsi.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassIscsi.name }}
  labels:
    {{- include "freebsd-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClassIscsi.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.driver.name }}
parameters:
  exportType: iscsi
  fsType: {{ .Values.storageClassIscsi.parameters.fsType | default "ext4" }}
  portal: {{ .Values.storageClassIscsi.parameters.portal | quote }}
  {{- /* CHAP authentication secret parameters */ -}}
  {{- if .Values.storageClassIscsi.chapSecret.name }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.storageClassIscsi.chapSecret.name | quote }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.storageClassIscsi.chapSecret.namespace | default .Release.Namespace | quote }}
  {{- end }}
allowVolumeExpansion: {{ .Values.storageClassIscsi.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClassIscsi.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClassIscsi.volumeBindingMode }}
---
{{- end }}
{{- /* NVMeoF Storage Class */ -}}
{{- if .Values.storageClassNvmeof.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassNvmeof.name }}
  labels:
    {{- include "freebsd-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClassNvmeof.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.driver.name }}
parameters:
  exportType: nvmeof
  fsType: {{ .Values.storageClassNvmeof.parameters.fsType | default "ext4" }}
  transportAddr: {{ .Values.storageClassNvmeof.parameters.transportAddr | quote }}
  transportPort: {{ .Values.storageClassNvmeof.parameters.transportPort | default "4420" | quote }}
  {{- /* NVMeoF DH-HMAC-CHAP authentication secret parameters */ -}}
  {{- if .Values.storageClassNvmeof.authSecret.name }}
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.storageClassNvmeof.authSecret.name | quote }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.storageClassNvmeof.authSecret.namespace | default .Release.Namespace | quote }}
  {{- end }}
allowVolumeExpansion: {{ .Values.storageClassNvmeof.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClassNvmeof.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClassNvmeof.volumeBindingMode }}
{{- end }}
