{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
{{- if and .Values.tls.caCert .Values.tls.clientCert .Values.tls.clientKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freebsd-csi.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freebsd-csi.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.caCert }}
  tls.crt: {{ .Values.tls.clientCert }}
  tls.key: {{ .Values.tls.clientKey }}
{{- end }}
{{- end }}
